on:
  push:
    branches:
    - master

jobs:
  run:
  working-directory: movielistapp
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          cd ..
          cd ..
          cd movielistapp
          cd movielistapp
          ls
          ls

