on:
  push:
    branches:
    - master

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
        
          cd ..
          cd ..
            echo "Contents of current directory:"
          ls
          cd client
          npm install
