on:
  push:
    branches:
    - master
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install node 16
        uses: actions/setup-node@v3
        with: 
          node-version: 16.x
      - name: Install NPM Dependencies - on server
        run: |
         cd server
         npm i
      - name: Install NPM Dependencies - on client
        run: |
         cd client
         npm i
      - name: start - server
        run: |
         cd server
         npm run dev
      - name: start - client
        run: |
         cd client
         npm run dev
         
      

