on:
  push:
    branches:
    - master
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install node 16
        uses: actions/setup-node@v3
        with: 
          node-version: 16.x
      - name: Install NPM Dependencies
        run: |
         cd server
         npm i
      

