on:
  push:
    branches:
    - master
defaults:
   run:
    working-directory: movielistapp
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          cd ..
          cd ..
          cd movielistapp
          cd movielistapp
          ls
          ls

