on:
  push:
    branches:
    - master
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install node 16
        uses: actions/setup-node@v3
        with: 
          node-version: 16.x
      

