on:
  push:
    branches:
    - master

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          ls
          cd ..
          ls
          cd ..
          ls
          cd movielistapp
          ls
          cd movielistapp
          ls
